### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by mlhale7**
For the purposes of publicly linking to content for our article, I wanted to add a folder containing documentation for TEI XML creation. I think we should continue to have the version on the Drive be the authoritative copy as it's easier for the whole team to edit and comment there. The documents within this folder so far are works in progress. Do comment with any changes that are needed before making these public.

### CODE REVIEW

**Comment by elizawilcox** [comment]
Edit step 6 in Workflow to direct to the accurate steps

**Comment by elizawilcox** [comment]
Add instructions for entities encoding in the <msDesc>

**Review by elizawilcox — COMMENTED** [review]
the XML_ID_Conventions look good to me, and I've added comments in the conversation for edits to the Edgeworth TEI Workflow in the conversation

**Comment by mlhale7** [comment]
@elizawilcox - thanks for this. Would you be able to make the edits on the document in Google Drive? I can re-download and add the edited file to this PR. PDFs aren't the best doc type for GitHub.

**Comment by elizawilcox** [comment]
@mlhale7 yes, I can do that! will let you know when changes have been made

**Review by hilaryhavens — APPROVED** [review]
This is great!  Thanks very much for adding the documentation to GitHub.  This will be great to link to in the article!

**Pull request merged**
