### PR TITLE
Editorial note

### PR DESCRIPTION
**Pull request by mlhale7**
## What does this Pull Request do?

This PR addresses the requested changes outlined in issue #34 

## How should this be tested?

Ensure that the change made to the text within editorialDecl matches expectations and that this change has been made across all XML files.

Additional changes had to be made to make all existing XML files validate. Please take a special look at Edgeworth_Bodleian_696_1819_14_17.xml. This letter had two figureDesc tags that were moved by me and might potentially not be situated as needed. I've attached the scans below. We can potentially discuss this more in our RA meeting instead and make changes after this PR is closed.
Edgeworth_Bodleian_696_1819-04-17_page06
Edgeworth_Bodleian_696_1819-04-17_page07

## Additional notes

Try to avoid copying and pasting the ref values for persName and placeName. There were several instances in which a ref value went to the Personography, but a place was referenced. There are likely more that I didn't catch since this mistake doesn't cause a validation error. Please also always remember to add a file extension (.xml).

### CODE REVIEW

**Comment by mlhale7** [comment]
@hilaryhavens - I think it may make sense to simply focus on the purpose of the PR and address this on Thursday. I had to change the file to make it validate so that I could run XSLT on it, but it's really beyond the scope of this PR and shouldn't hold everyone else up for a few days. The problem is that `</figure>` can't be placed after a `</lb>` and still have the file validate. Typically figure seems to be being used in TEI for an added image file versus something in-line with text. Honestly, I think I need to look at this more.

**Comment by hilaryhavens** [comment]
Thanks, Meredith!  We can talk about where precisely the ```<figure>``` tag is placed in each case on Thursday, but this is related to my first point - that we should be doing ```<figure><figDesc></figDesc></figure>``` instead of ```<figure><figDesc></figDesc> some text related to the image that may span multiple lines</figure>``` .  Does this answer the question?  Thanks!

**Comment by elizawilcox** [comment]
@mlhale7 @hilaryhavens I initially attempted (as Meredith noted) to try and capture the text interruptions, but if that's not possible, I can make edits to the workflow after Thursday's meeting when we discuss to note that the priority for describing figures is description, not necessarily total replication since a <figure> can't go across <lb/> tags.

**Comment by mlhale7** [comment]
People are welcome to look closer at the changes I've made to that single file here - Encoded Letters/Edgeworth_Bodleian_696_1819_04_17.xml

Otherwise I'd appreciate feedback on whether issue #34 has been fully addressed. If that issue has been addressed, please approve. If it hasn't, please comment.

**Review by hilaryhavens — APPROVED** [review]
This looks great - thanks for adding in the paragraph about ME grammar / spelling!

**Comment by rrunia** [comment]
Hi all,
I agree with Hilary's suggestions.
Cheers,
Robin

Robin Runia, Ph.D.
Professor of English
Kellogg Endowed Professorship in English
Xavier University of Louisiana
1 Drexel Drive, Box 89
New Orleans, LA 70125

***@***.***
she/her/hers

Faculty Editor, XULANEXUS<https://digitalcommons.xula.edu/xulanexus/>
Series Editor, <https://udpress.udel.edu/book-series/early-modern-feminisms/> Early Modern Feminisms, <https://udpress.udel.edu/book-series/early-modern-feminisms/> University of Delaware Press<https://udpress.udel.edu/book-series/early-modern-feminisms/>
Editor, Maria Edgeworth Letters Project<https://mariaedgeworth.org/>
________________________________

**Pull request merged**
